language: python
dist: trusty
sudo: required

python:
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-numpy python-pyqt5
script:
  - pip install -e .
  - cd ./tests
  - py.test