language: python
dist: trusty
sudo: required

python:
  - "3.4"
  - "3.5"
  - "nightly"

install:
  - pip install --upgrade pip
  - pip --version
  - pip install pyqt5
  - pip install numpy

script:
  - python3 setup.py build_ext
  - cd ./tests
  - export PYTHONPATH="../src"
  - py.test -v