language: python
sudo: required

python:
  - "3.4"
  - "3.5"
  - "nightly"


# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - ./miniconda.sh -b -p $HOME/miniconda
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy pyqt5
  - python setup.py build_ext

script:
  - cd ./tests
  - export PYTHONPATH="../src"
  - py.test -v