language: python
dist: trusty
sudo: required

python:
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-numpy python3-pyqt5 g++ libpython3-dev
script:
  - export PYTHONPATH="./src"
  - cd src/urh/cythonext
  - python3 build.py
  - cd ../../../tests
  - py.test