language: python
dist: trusty
sudo: required

python:
  - "3.4"
  - "3.5"
  - "nightly"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-numpy python3-pyqt5

script:
  - pip install -e .
  - cd ./tests
  - export PYTHONPATH="../src"
  - py.test -v