language: python
sudo: required
dist: trusty

python:
  - "3.4_with_system_site_packages"

# Install packages
install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5 python3-numpy

script:
  - cd ./src/urh/cythonext
  - python build.py
  - cd ../../../tests
  - export PYTHONPATH="../src"
  - py.test