language: python
dist: trusty
sudo: required

python:
  - "3.5"
  - "3.6"

before_script:
  - sudo apt-get install -qq libegl1-mesa
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - "pip install -r requirements.txt"

script:
  - python3 src/urh/cythonext/build.py
  - pytest -v tests
