language: python
dist: trusty
sudo: required

python:
  - "3.4"
  - "3.5"
  - "nightly"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-numpy python3-pyqt5

install:
  - pip install pyqt5
  - pip install numpy

script:
  - python3 setup.py build_ext
  - cd ./tests
  - export PYTHONPATH="../src"
  - py.test -v